build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - apt-get update -y
    - apt-get install -y python3 python3-pip virtualenv
    - virtualenv --python=python3 ~/env/
    - source ~/env/bin/activate
    - pip install .
    - echo "Run voithos help"
    - voithos --help
    - echo "Run voithos version"
    - voithos version
    - echo "Package voithos"
    - python setup.py sdist
    - find . | grep voithos.*tar.gz
